server_name: 'Generic Server'

admin_only:
    enabled: false
    kick:
        enabled: false
        default: true
    kick_message: '&eServer is currently undergoing maintenance'

# Messaging Modes: 0 = DEFAULT/ 1 = REPLACE/ 2 = WARN
# leave message blank to send no warning message
chat:
    clean:
        enabled: false
        mode: 0
        strict: false
        warn:
            enabled: true
            message: '&cPlease do not swear!'
    lowercase: false

messages:
    join: '&6[PLAYER] &bjoined the game'
    quit: '&6[PLAYER] &bleft the game'

motd:
    ingame: '&2Welcome to my server!'
    server: '&5Join this server!'

players:
    count: 0
    id_base: 0

# format | swear (lowercase):replacement (case-insensitive)
swears:
    - poop:doo-doo
    - ass:butt